### ISSUE TITLE
Possible to share the model evaluation code? 

### ISSUE THREAD

**Issue by joelkuiper** [bepnye/EBM-NLP#1]
Hey all, 

I'm having a bit of trouble with reproducing the numbers in your paper https://arxiv.org/pdf/1806.04185.pdf using a similar BiLSTM-CRF (https://github.com/zalandoresearch/flair to be precise), would it be possible to share the code you used for evaluation? Since the gold test set appears to have quite a few "gaps" and I'm currently evaluating on the merged sequence of PIO, which seems a bit different from your token level results?

**Comment by bwallace** [comment]
Yes, thanks for the ping on this; @bepnye will post the vanilla model in the paper (+ eval code), as well as [Roma's NAACL model](https://arxiv.org/abs/1805.00097) asap

**Comment by bepnye** [comment]
Hey Joël,

Our collaborator Roma tuned and evaluated the LSTM-CRF. I've reached out to
her for the code and will pass it along to you as soon as I can.

Thanks,
Ben

**Comment by mladvladimir** [comment]
Hi, 
I trained model with default parameters in https://github.com/bepnye/EBM-NLP/blob/master/acl_scripts/lstm-crf/model/config.py, using PubMed-w2v.txt word embeddings.
By running evaluate.py I've got   
`acc 67.69 - f1 23.11 - recl 16.21 - prec 40.26`.
- Should I use these parameters to obtain results similar to those published in paper?
- Have evaluation method from code been used for estimation 'first-phase' metric ( P,I and O labels) for biLSTM-CRF model mentioned in paper? 
- Do you have any suggestions for improvement?

Regards

**Comment by bepnye** [comment]
I've pushed an updated version of the data initialization and evaluation for the BiLSTM-CRF. Our model can be found in acl_scripts/lstm-crf/ with the everything needed for training and evaluation (the word vectors we used are available [here](http://www.ccs.neu.edu/home/bennye/EBM-NLP/PubMed-w2v.txt.zip)).

This model learns the merged PIO elements jointly, and the results are computed per-element for evaluation purposes.

If you have any further questions or issues, please let me know!
