### ISSUE TITLE
Tokens should be split on newline

### ISSUE THREAD

**Issue by successar** [bepnye/EBM-NLP#3]
https://github.com/bepnye/EBM-NLP/blob/41dcba1d8f7a181ed8063f1462548ff090be6e4c/ebm_nlp_demo.py#L58

**Comment by bwallace** [comment]
yes this is for v2 specifically I believe

**Comment by bepnye** [comment]
Yes, this example was still using v1.0 conventions. Updated processing to point to v2.0 and use the new delimiters.
