### ISSUE TITLE
Can't access the brat server

### ISSUE THREAD

**Issue by DavidBegert** [bepnye/EBM-NLP#5]
That annotations found at: http://100.25.69.239:8001/index.xhtml#/ebm-nlp/
Cannot be accessed.

I'm hoping to download the raw .ann and .txt files that were annotated. Is this possible?

Thanks, 
David

**Comment by bepnye** [comment]
Hi David,

You can download the annotations directly from the github repository
<https://github.com/bepnye/EBM-NLP>. ebm_nlp_demo.py contains an example
for generating brat-compatible files. Let me know if you have any issues.

Thanks,
Ben

**Comment by DavidBegert** [comment]
Thanks! I think it managed to get it working on ebm_nlp_2_00 . Looks like there are 4801 annotations total. What is the difference between ebm_nlp_2_00 and ebm_nlp_1_00 ?  It seems like (almost) all the annotations were found in ebm_nlp_2_00.

**Comment by bepnye** [comment]
The only important differences is the update to the test set. In 2.0, the
documents selected for expert annotation were held constant between all
PICO elements and annotation phases.

**Comment by rsingh2083** [comment]
> Thanks! I think it managed to get it working on ebm_nlp_2_00 . Looks like there are 4801 annotations total. What is the difference between ebm_nlp_2_00 and ebm_nlp_1_00 ? It seems like (almost) all the annotations were found in ebm_nlp_2_00.

Hi ,

can you please help how to run this ? 
`python ebm_nlp_demo.py`
Doesnt give any output at all, just blank cursor

**Comment by bepnye** [comment]
> Hi ,
> 
> can you please help how to run this ?
> `python ebm_nlp_demo.py`
> Doesnt give any output at all, just blank cursor

This file is a library of utility functions demonstrating some common ways you may want to manipulate the annotations. If you're trying to train a model, look at the scripts available in the `model` directory.

**Comment by elkotito** [comment]
@bepnye Do you have raw brat files for the dataset? I see a way to generate ones from tokens, but I am interested in brat files without messy spaces which come from tokenization.
