### ISSUE TITLE
What tokenizer was used to obtain .tokens files?

### ISSUE THREAD

**Issue by elkotito** [bepnye/EBM-NLP#6]
Hi, 

What tokenizer was used to obtain .tokens files? I haven't found such information in the original paper. I only know that BRAT was used for annotation. I used https://github.com/nlplab/brat/blob/master/server/src/tokenise.py code to tokenize text, but I got different tokens than the ones in .tokens files anyway.

Thanks in advance!

**Comment by bepnye** [comment]
NLTK's default tokenizer (`import nltk; tokenizer = nltk.word_tokenize`).

**Comment by elkotito** [comment]
@bepnye Which version of NLTK?

**Comment by bepnye** [comment]
The dataset was generated with 3.2.5 but there do not seem to be significant changes with 3.3. The only post-processing step was to revert NLTK's conversion of opening quotation marks to double apostrophes and closing quotation marks to double backticks.
